### ISSUE TITLE
Fixing Issues in the `sample.js` File

### ISSUE THREAD

**Issue by ericdrobinson** [AdobeXD/typings#42]
I downloaded this repository, unzipped it, opened the folder in Visual Studio Code (v1.33.0), opened the `sample.js` file, and was greeted to the following two errors:

![image](https://user-images.githubusercontent.com/9142587/55673438-2c0dd500-5876-11e9-9a39-ca7780b1edf4.png)

These are pretty simple to fix.

## Fixing the `RootNode` Type Error

This problem occurs because the `sample.js` scope doesn't have the `RootNode` type imported yet, even though it's used in a JSDoc `parameter` declaration:

```js
/**
 * @param {Selection} selection
 * @param {RootNode} documentRoot
 */
```

There are two ways to fix this:

1. Import the `RootNode` type (class).
1. Use TypeScript's "[`import` types](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-9.html#import-types)".

If you chose the second route, the code excerpt above would become:

```js
/**
 * @param {Selection} selection
 * @param {import('scenegraph').RootNode} documentRoot
 */
```

Note that this does not actually import the type into the `sample.js` "module"'s scope, but enables it and consumers to get proper type handling.

## Fixing the `File | Folder` Type Error

This problem refers to this code from [line 23](https://github.com/AdobeXD/typings/blob/c8459a6466ab69da08f08fd4ec1d04fa17dbdad5/sample.js#L23):

```js
newFile.write("Hello, world!");
```

This is actually a bit more complicated than the previous error as there are **three** things going on:

1. There is no `Folder` type defined in the current scope.
1. The `File` type specified refers to the global [Web DOM `File`](https://developer.mozilla.org/en-US/docs/Web/API/File) type.
1. The `Folder.createEntry` method returns **either** a UXP `File` or a UXP `Folder` (and the code assumes it returns a UXP `File` instance).

To handle all of these issues and provide a safer usage example, do the following:

1. Import the UXP `File` type.
1. Add a type guard to the call to `write()`.

Put together the above looks like this:

```js
// At the top of sample.js
const UXPFile = require("uxp").storage.File;

// ...

// Replace Line 23 with this:
if (newFile instanceof UXPFile) {
    newFile.write("Hello, world!");
}
```

---

With these changes you will find that your JavaScript sample is now error-free! Hurray!

I decided to explain these here in the hopes that it will be more instructive than a simple PR. Hope this helps!

**Comment by pklaschka** [comment]
I'll now fix the first issue. Unfortunately, `File` and `Folder` aren't exported (that was wrong in the typings – my bad) in the storage module, meaning you can't require them and therefore, `instanceof` won't work. They are, in fact, just "`static`" classes, as per the documentation, and 

```js
require("uxp").storage.File;
```

simply evaluates in `undefined`. To my knowledge, this aspect of the APIs simply cannot get *modelled* with typings 😐  ...

**Comment by ericdrobinson** [comment]
@pklaschka Went ahead and installed XD and played around with stuff. You're totally correct:

```ts
require("uxp").storage.File === undefined
```

... which tells us something **_very_** important:

**There is no such thing as a `File` class!**

Adobe's [`storage` documentation](https://adobexdplatform.com/plugin-docs/reference/uxp/module/storage.html) leaves quite a bit to be desired. One example is the terminology: "static class"? Typically a static class is a class that **can't be instantiated**. If that is the case, then how are you supposed to get a `File` instance from a `static class File`?

The answer is that you don't. What you're dealing with here is an `interface`. In fact, from what I can tell, all of the `class` declarations in the `uxp.d.ts` file should absolutely be declared as `interface`s.

That's just the beginning, though. As it turns out, the `uxp.d.ts` file is way out of sync with the actual API according to the latest XD API docs. One _**major**_ example is that [`Folder.createEntry`](https://github.com/AdobeXD/typings/blob/df6cf307c0b8178fc867bf098cf549b185fddc25/types/uxp.d.ts#L259) doesn't even exist on the [`Folder`](https://adobexdplatform.com/plugin-docs/reference/uxp/module/storage.html#module-storage-folder) type...

As such, you could replace `createEntry` with `createFile` and your ambiguity problem (`File` vs `Folder`) goes away.

**However**, that still leaves the [`Folder.getEntry`](https://github.com/AdobeXD/typings/blob/df6cf307c0b8178fc867bf098cf549b185fddc25/types/uxp.d.ts#L284) method with the same ambiguity problem. We should fix this regardless.

# Fixing the `File` vs `Folder` Ambiguity

As both `File` and `Folder` are **_not_** defined as ES2015 `class`es, they do not support standard identification approaches (see: [`constructor.name`](https://stackoverflow.com/a/332429/5285364)). Well, how do we allow the user to distinguish between the two in a type-safe manner when they experience this ambiguity?

We can cheat a little.

We know that both `File` and `Folder` extend the `Entry` type. That interface provides both the `isFolder` and `isFile` properties. The thing is that you will _**never**_ have a case wherein `folderInstance.isFile` is `true` and vice-versa. This means that we can do the following in the definition of the `Folder` interface:

```ts
readonly isFile: false;
readonly isFolder: true;
```

and similarly in the `File` interface:

```ts
readonly isFile: true;
readonly isFolder: false;
```

Then in your `sample.js` file you can run the check as follows:

```ts
const newFile = await tempFolder.getEntry("tempfile.txt");
if (newFile.isFile) {
    newFile.write("Hello, world!");
}
```

If you make those modifications you will see that there is now no error reported. This is because TypeScript is smart enough to notice that `isFile` is now defined on **_both_** the `Folder` and `File` interfaces and that it is _only_ `true` on one of them! This allows the language to correctly narrow the type to `File` as expected here.

The `else` clause will not automatically narrow to the `Folder` type. The workaround is to write it as `else if (newFile.isFolder)`. This works fine in my tests.

# Other Issues

There are a number of other things I've noticed about `uxp.d.ts` that I'll bring up as inline comments. Hopefully they will prove helpful!

**Comment by ericdrobinson** [comment]
>There are a number of other things I've noticed about uxp.d.ts that I'll bring up as inline comments.

Correction: I can't do this as inline comments can only be applied to changes. I will open new issues for them instead.

**Comment by ericdrobinson** [comment]
Also, when the types are changed from `static class` to `interface`, any `static` methods can be straight-up removed. None of the `static` methods in the current `uxp.d.ts` file exist in the [documentation](https://adobexdplatform.com/plugin-docs/reference/uxp/module/storage.html) anyway...

**Comment by peterflynn** [comment]
One quick note here: `createEntry()` has been deprecated since before plugin APIs actually launched publicly -- it's not even listed in our public docs anywhere.  I'd suggest removing that from the sample (and the typings overall if it's in there) and having the sample use the official API `createFile()` instead -- which _is_ strongly typed as returning a File.

If you're writing to an existing file though, which you retrieved via <code><i>get</i>Entry()</code>, then the `isFile` check noted above is the way to do.

**Comment by ericdrobinson** [comment]
>If you're writing to an existing file though, which you retrieved via `getEntry()`, then the `isFile` check noted above is the way to do.

@peterflynn I have to admit that not being able to do:

```js
const UXPFile = require("uxp").storage.File;
if (folderOrFile instanceof UXPFile)
    // File stuff...
```

felt incredibly clumsy. I understand the desire to hide constructors from users when they don't do anything useful, but there are [ways](https://stackoverflow.com/a/21731713/5285364) to work around that issue while maintaining standard usability.

This isn't limited to `File` and `Folder` classes, either. It independently came up with [`scenegraph.SceneNode`](https://forums.adobexdplatform.com/t/typeof-scenegraph-scenenode-is-undefined/934) for instance.

**Comment by peterflynn** [comment]
`instanceof` should work just fine for scenegraph classes -- we use that all the time in sample plugins.

I can't speak to why the UXP APIs opted to hide the constructors / "class definitions" and use `is*` flags instead, since those APIs were designed and built by a separate team.  One reason may be that UXP tries to follow web paradigms as much as possible, for developer familiarity, and it's not particularly common to use `instanceof` for type checking browser objects.  @kerrishotts might have more insight here though.

**Comment by ericdrobinson** [comment]
>`instanceof` should work just fine for scenegraph classes -- we use that all the time in sample plugins.

Please check out the [linked forum post](https://forums.adobexdplatform.com/t/typeof-scenegraph-scenenode-is-undefined/934). The `SceneNode` class is special in that attempting to access it directly results in `undefined` the same way that `storage.File` and `storage.Folder` are undefined.

>it's not particularly common to use `instanceof` for type checking browser objects.

Hmm. That has not been my experience. Seems [pretty ubiquitous](https://stackoverflow.com/questions/384286/javascript-isdom-how-do-you-check-if-a-javascript-object-is-a-dom-object) for browser objects...

I guess a better comparison would be with the [NodeJS FileSystem APIs](https://nodejs.org/api/fs.html) (which allow you to use `instanceof`) but the current UXP Storage APIs are a _far cry_ from those. They honestly feel far more similar to the old [ExtendScript File/Folder API](http://estk.aenhancers.com/3%20-%20File%20System%20Access/using-file-and-folder-objects.html)... except that even _that_ implementation allowed you to use `instanceof`...
