### ISSUE TITLE
SceneNodeList "type" should move to scenegraph.d.ts

### ISSUE THREAD

**Issue by ericdrobinson** [AdobeXD/typings#52]
The [`SceneNodeList`](https://adobexdplatform.com/plugin-docs/reference/SceneNodeList.html) class should not be in the global context. Actual attempts to access the `SceneNodeList` directly in a command script results in `undefined` (it's not actually a global).

Further, this should probably be an **interface** rather than a class as there does not appear to be a way to create new instances yourself.

Therefore I would recommend moving the `SceneNodeList` declaration into `scenegraph.d.ts`, (the only location the type is actually referenced) and simultaneously convert it to an interface.

**Comment by pklaschka** [comment]
I've done this in the mega PR as well in order to not have many releases for this version. I'll (really) merge it later today (unless you open yet another issue that can get fixed with this PR 😉).

**Comment by ericdrobinson** [comment]
>unless you open yet another issue that can get fixed with this PR 😉

Hold onto your pants... 😉
