### ISSUE TITLE
Reimagine structure with samles etc.

### ISSUE THREAD

**Issue by pklaschka** [AdobeXD/typings#57]
As proposed by @ericdrobinson in https://github.com/AdobeXD/typings/issues/54#issuecomment-506982532:
> Repo Structure - New Issue?
> I would like to suggest that the jsconfig.json and sample.js file get moved into a sample or 
> example folder that's separate from the top level. A tsconfig.json file at the top level then makes > the most sense. This will allow a clear separation of TypeScript and JavaScript files while allowing > you to have a tsconfig.json file that's designed specifically for writing the declaration files.
> 
> Thoughts?

**Comment by pklaschka** [comment]
The thing is that this would mean that the `sample.js` file wouldn't work when cloning the repo, anymore, since the `jsconfig.json` is meant to be placed at the project root folder with a `types` folder as a sibling (the way it is now). This makes using the typings for JS basically a copy-and-paste solution in VSCode as one simply has to copy `types` and `jsconfig.json` into the project directory to use it.

**Comment by ericdrobinson** [comment]
>This makes using the typings for JS basically a copy-and-paste solution in VSCode as one simply has to copy `types` and `jsconfig.json` into the project directory to use it.

If that's the case then it might be beneficial to call that out in the Readme. People who are used to TypeScript may understand that but a newbie to type declarations may not understand the purpose of a `jsconfig.json` file.

Another option to consider would be to place a `tsconfig.json` file within the `types` folder. ... ... I'm... not so convinced by this but it is how I have managed it in my testing environment...

All of this goes away, of course, once the types are added to Definitely Typed or some such.

**Comment by pklaschka** [comment]
@ericdrobinson I've documented this in the [repo's wiki](https://github.com/AdobeXD/typings/wiki/Autocompletion-in-editors-and-IDEs#visual-studio-code) and linked to it in the README. Do you think that this should get put into the README? Another option (allowing for instructions to be a part of the repo) could be to have the wiki as a submodule of this repo (in a folder called `wiki` or something like that)...

**Comment by ericdrobinson** [comment]
>Do you think that this should get put into the README?

No, I think the wiki is a good place for such information. However, I think the README should certainly have a "Getting Started" section that gives the basic overview. It can then point to the wiki for further information and IDE-specific setup.

Example:

# Getting Started
These Type Declaration files provide your IDE (e.g. [Visual Studio Code](https://code.visualstudio.com/) or [WebStorm](https://www.jetbrains.com/webstorm/)) with information about the XD API surface, enabling type checking, atuocomplete suggestions, and more. To get started, simply copy the following resources from this repo into your project's main directory:

1. The `jsconfig.json` file.
1. The `types` directory.

Your IDE may require further setup to take full advantage of the types. Please see [this wiki page](https://github.com/AdobeXD/typings/wiki/Autocompletion-in-editors-and-IDEs#editor--ide-specific-instructions) for more.

---

Providing an example image/gif of autocomplete in action to accompany the text would also go a very long way to improving things.
