### ISSUE TITLE
LinearGradient and RadialGradient do not exist in scenegraph

### ISSUE THREAD

**Issue by GDreyV** [AdobeXD/typings#60]
Please adjust names of these classes as it doesn't work now.
https://forums.adobexdplatform.com/t/what-namespace-is-lineargradientfill/942/2
https://github.com/AdobeXD/plugin-docs/issues/179

**Comment by pklaschka** [comment]
Please see https://github.com/AdobeXD/typings/pull/41. I'm regularly pinging Adobe staff about this (among other places, in the forum post you've mentioned). Same reasoning as in https://github.com/AdobeXD/typings/issues/61...
