### ISSUE TITLE
make RenditionSettings.type strongly types

### ISSUE THREAD

**Issue by GDreyV** [AdobeXD/typings#63]
RenditionSettings.type can have only specific value so I suppose it must be strongly typed, like:
```
/**
  * File type: RenditionType.PNG, JPG, PDF, or SVG
  */
    type: "PNG" | "JPG" | "PDF" | "SVG";
```
Really documentation is unclear if RenditionType stands for specific type or just a way to describe values.

**Comment by GDreyV** [comment]
I used `application.RenditionType.PNG` so I guess it's hardcoded object/class with static properties.

**Comment by pklaschka** [comment]
Agreed. I'll fix this in the next release.
