### ISSUE TITLE
Is `Line.setSTartEnd` typo?

### ISSUE THREAD

**Issue by tsuchinaga** [AdobeXD/typings#66]
I think `setSTartEnd` is a typo in `setStartEnd`.

https://github.com/AdobeXD/typings/blob/master/types/scenegraph.d.ts#L885

**Comment by pklaschka** [comment]
I'm currently unable to update the repo as I'm in the middle of exams and don't have enough time. Until August 8th, I'll review (and merge) pull requests, view comments, etc., but please understand that I don't have the time to actively update the repo for these next two weeks. Thank you very much for your understanding 🙂
