### ISSUE TITLE
SceneNode doesn't contain addChild, but all derived classes/types do, shouldn't it be on SceneNode itself?

### ISSUE THREAD

**Issue by Triggs9** [AdobeXD/typings#68]
When following the [quick start](https://adobexdplatform.com/plugin-docs/tutorials/quick-start/) it uses:

`selection.insertionParent.addChild(newElement);`

while the [Selection](https://github.com/AdobeXD/typings/blob/d56685bd8e346d1ffc7e43e6cdc79e2945778407/types/index.d.ts#L61) in the global namespace uses [SceneNode](https://github.com/AdobeXD/typings/blob/d56685bd8e346d1ffc7e43e6cdc79e2945778407/types/scenegraph.d.ts#L402) as its [insertionParent](https://github.com/AdobeXD/typings/blob/d56685bd8e346d1ffc7e43e6cdc79e2945778407/types/index.d.ts#L91) type. 

Issue:

SceneNode type contains no direct relation to addChild, but all derivatives do including:

- [GraphicNode ](https://github.com/AdobeXD/typings/blob/d56685bd8e346d1ffc7e43e6cdc79e2945778407/types/scenegraph.d.ts#L600)
- [Artboard ](https://github.com/AdobeXD/typings/blob/d56685bd8e346d1ffc7e43e6cdc79e2945778407/types/scenegraph.d.ts#L703)
- [BooleanGroup ](https://github.com/AdobeXD/typings/blob/d56685bd8e346d1ffc7e43e6cdc79e2945778407/types/scenegraph.d.ts#L939)
- [Group ](https://github.com/AdobeXD/typings/blob/d56685bd8e346d1ffc7e43e6cdc79e2945778407/types/scenegraph.d.ts#L1141)
- [SymbolInstance ](https://github.com/AdobeXD/typings/blob/d56685bd8e346d1ffc7e43e6cdc79e2945778407/types/scenegraph.d.ts#L1185)
- [RepeatGrid](https://github.com/AdobeXD/typings/blob/d56685bd8e346d1ffc7e43e6cdc79e2945778407/types/scenegraph.d.ts#L1229)
- [RootNodeClass ](https://github.com/AdobeXD/typings/blob/d56685bd8e346d1ffc7e43e6cdc79e2945778407/types/scenegraph.d.ts#L1323)

```
...

/**
     * Adds a child node to this container node. You can only add leaf nodes this way; to create structured subtrees of content, use commands.
     * @param {SceneNode} node Child to add
     * @param {number} index Optional: index to insert child at. Child is appended to end of children list (top of z order) otherwise.
     */
    addChild(node: SceneNode, index?: number): void;

    /**
     * Inserts a child node after the given reference node.
     * @param {SceneNode} node Child to add
     * @param {SceneNode} relativeTo New child is added immediately after this existing child
     */
    addChildAfter(node: SceneNode, relativeTo: SceneNode): void;

    /**
     * Inserts a child node before the given reference node.
     * @param {SceneNode} node Child to add
     * @param {SceneNode} relativeTo New child is added immediately before this existing child
     */
    addChildBefore(node: SceneNode, relativeTo: SceneNode): void;

    /**
     * Removes all children from this node. Equivalent to calling removeFromParent() on each child in turn, but faster.
     */
    removeAllChildren(): void;

...
```

Solution:

SceneNode contains:

```
addChild()
addChildAfter
addChildBefore
removeAllChildren()
```

OR:

i assume the auto compiler found one derived instance of SceneNode, that didn't contain these methods, but then the insertionParent should be all acceptable derived classes such as:

`
insertionParent: SceneNode | Artboard | GraphicNode (etc...);
`

**Comment by pklaschka** [comment]
Hi @Triggs9.

First of all: Thank you for the issue.

`SceneNode` is the class (or better: interface) all other types inherit from. This also includes things like the `GraphicNode`, which, in fact, aren't a `Group` and therefore do not contain the "child management methods" (out of context, this sounds so wrong :rofl:).

As the other types implement the `SceneNode` interface, 

> but then the insertionParent should be all acceptable derived classes such as:
> 
> `insertionParent: SceneNode | Artboard | GraphicNode (etc...);`

shouldn't be necessary (as it is implied by `SceneNode` being the super class/interface).

All in all, I tend to believe that [the documentation](https://adobexdplatform.com/plugin-docs/reference/selection.html#selectioninsertionparent--scenenode) documenting the type of `insertionParent` to be `SceneNode` is a bit too broad and should, probably, be something like `Group`. Having said that, I try to keep the typings up-to-date with the docs (to keep them somewhat maintainable), meaning in case `insertionParent` actually should be a `Group`, that's an issue for https://github.com/adobexd/plugin-docs.

All in all, for now, the correct way to do this (per documentation and typings) would be to add:

```js
if (selection.insertionParent instanceof Group) {
  // Do something with the group node here
}
```

The typings, however, are (according to the docs) accurate in this case...

I hope this helps,
Best,
Pablo

**Comment by pklaschka** [comment]
I'm closing this for now. Feel free to re-open as needed; but as far as I understand it, this currently isn't an issue in the typings.

Best,
Pablo
