### ISSUE TITLE
Suggestion: Call out custom type name overrides in ReadMe

### ISSUE THREAD

**Issue by ericdrobinson** [AdobeXD/typings#72]
PR #70 changed the `Selection` type declaration to be `XDSelection`. It may be helpful for users to have this explicitly called out (with explanation for _why_) in the ReadMe.

**Suggestion:** Add a new section to the ReadMe file (called something like "Notes" or "Errata") that calls out customizations like this and includes a blurb for their raison d'être.

**Comment by pklaschka** [comment]
@ericdrobinson The funny thing is: I wanted to implement this tomorrow, anyway. You're too fast at creating issues :stuck_out_tongue_winking_eye:.

I'll also (before creating the release) rename the `LinearGradient` (I've waited for too long for the docs to update this :neutral_face:), cf. #41, and will then include these as "exceptions" in the section where we've specified that the typings follow the docs.
