### ISSUE TITLE
Typings for Photoshop?

### ISSUE THREAD

**Issue by partlyhuman** [AdobeXD/typings#81]
Are there any declarations for the photoshop API (https://developer.adobe.com/photoshop/uxp/2022/ps_reference/)? This would be very helpful for developing plugins & PSJS scripts.

**Comment by pklaschka** [comment]
For Photoshop Host app APIs (this unfortunately doesn't include the core UXP types), type definitions get published to DefinitelyTyped as `@types/photoshop` (cf. https://www.npmjs.com/package/@types/photoshop).

They seem to be a little out of date, as of right now, but these are "the" Photoshop types (and thus, probably your  best bet).

Please feel free to re-open this issue in case this doesn't answer your question.

Thanks,
Pablo
